name: Secure App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

        - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest bandit pip-audit safety

      - name: Ejecutar pruebas automatizadas
        run: |
        python -m pytest -q


    - name: Escanear dependencias con Safety
      run: |
        pip install safety
        safety check --full-report || true
