name: CI/CD Secure App

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: |
          pip install pytest
          pytest -q

      - name: Escaneo de seguridad con Bandit
        run: |
          pip install bandit
          bandit -r .

      - name: Escaneo de dependencias con pip-audit
        run: |
          pip install pip-audit
          pip-audit --output pip_audit.txt || true
